MD013: false     # line-length
MD024: false     # Multiple headers with the same content
MD036: false     # no-emphasis-as-heading
MD041: false     # First line in file should be a top level heading (for deprecated warning)
