os: linux

language: node_js

node_js:
  - 12.14.0

# Safelist
branches:
  only:
    - master

cache:
  npm: true
  pip: true

jobs:
  include:
    - before_script:
        - npm ci
      script:
        - npm run test:markdown
        - npm run test:eslint
        - npm run test:stylelint
        - npm run test
        - npm run build
        - npm run build:example
    - after_success:
        - npm run coverage