os: linux

language: node_js

node_js:
  - 12.14.0

# Safelist
branches:
  only:
    - master

cache:
  npm: true
  pip: true

jobs:
  include:
    - before_script:
        - npm ci
      script:
        - npm run test:markdown
        - npm run test:eslint
        - npm run test:stylelint
        - npm run test
        - npm run build
        - npm run build:example
        - npm run create:gh-pages
        - cd gh-pages
      deploy:
        provider: pages
        cleanup: false
        token: $GITHUB_TOKEN
        keep_history: false
        edge: true
        commit_message: Deploy Travis CI to %{target_branch} branch
        on:
          branch: master
    - after_success:
        - npm run coverage
